name: variables
on: push
jobs:
  job1:
    env:
     MY_NAME: "prabhas"
    runs-on: ubuntu-latest
    steps:
      - name: "env variables"
        run: |
         echo: " my name is $MY_NAME"
         pwd
         hostname
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: " printing name"
        run: |
          echo " print {{github_ref-name}}
          pwd
      
      
