name: test-1
on:
  workflow_dispatch:
     inputs:
       environment:
         description: Select environment 
         required: true
         default: dev
         type: choice
         options:
           - dev
           - test
           - UAT
           - prod
       artifact_tag: 
        description: select tag to deploy
        required: true
        type: string
jobs:
  job1: 
    env:
     MY_NAME: "prabhas"
    runs-on: ubuntu-latest
    steps:
      - name: "env variables"
        run: |
         echo " my name is $MY_NAME"
         echo " this is uploaded by ${{inputs.environment}} and the tag is ${{inputs.artifact_tag}}"
         if [ ${{inputs.environment}} == 'dev' ] || [ ${{inputs.artifact_tag}} == 'v2' ] && [ ${{github.actor}} == 'prabhas2612' ] 
           echo " this is legit to trigger"
          
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: " printing name"
        run: |
          echo " print ${{github.sha}} "
          echo " this workflow is run by ${{github.actor_id}} "
          pwd
      
      
